### ISSUE TITLE
How to use EnsureUserAsync 

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/msgraph-sdk-dotnet-contrib#45]
Please add a sample for using "EnsureUserAsync" with GraphServiceClient graphClient

**Comment by pschaeflein** [comment]
Have you looked at the [test project](https://github.com/microsoftgraph/msgraph-sdk-dotnet-contrib/blob/b751543fce1ce5869890cf17546ca7bcd3587243/test/WebRequestTests.cs#L216)?

```csharp
await gsc.GraphServiceClient
  .SharePointAPI(mockWebUrl)
  .Web
  .Request()
  .EnsureUserAsync("alexw");
```
