### ISSUE TITLE
Issue using Microsoft Graph SDK filter clause in an Calendar/Events query.

### ISSUE THREAD

**Issue by johnpike365** [microsoftgraph/msgraph-sdk-dotnet-contrib#57]
Issue using Microsoft Graph SDK filter clause in an Calendar/Events query. Here is the actual c# code that I am having the problem with: var results = await eventServiceClient.Users[users[i].Id].Calendar.Events.Request().Top(999).Select("Start,End,Body,BodyPreview,Subject,CreatedDateTime,LastModifiedDateTime,Type").Filter("startDateTime ge 2023-03-20T08:00:00").GetAsync();

**Comment by pschaeflein** [comment]
This repository is for the [Graph.Community library](https://www.nuget.org/packages/Graph.Community/).

I believe this issue should be raised in the SDK repo at https://github.com/microsoftgraph/msgraph-sdk-dotnet
